### ISSUE TITLE
Provide instructions for self-hosting the data

### ISSUE THREAD

**Issue by arthurlutz** [MrBreadWater/project-kronos-data-collector#2]
Project looks awesome, please provide instructions on how to host the server side of the project.

**Comment by MrBreadWater** [comment]
You mean uploading the timelapses to your own alternate server? Well, it's possible, yes. But that's not really what this was intended for. I suppose I could add that, if it's a feature people are interested in.

**Comment by MrBreadWater** [comment]
Duplicate issue. https://github.com/MrBreadWater/project-kronos-data-collector/issues/3
