### ISSUE TITLE
Configuration options for sending the data to self-hosted server

### ISSUE THREAD

**Issue by arthurlutz** [MrBreadWater/project-kronos-data-collector#3]
Provide configuration options so one can send their to they own server / S3 / minio buckets. Needed for #1

**Comment by MrBreadWater** [comment]
This is the same as the other issue request, if I'm understanding correctly. I'll close the other one as a duplicate.

If it's really something people want, I can add an option to upload the data to their own S3 Buckets as well as mine. But that's not the main goal, so it may be a few weeks before I push out that update if it's something people want.
