### ISSUE TITLE
Will the resulting neural network be open source ? 

### ISSUE THREAD

**Issue by arthurlutz** [MrBreadWater/project-kronos-data-collector#5]
Will the resulting neural network be open source ? WIll it be a commercial product ? Will the community benefit from contributing their stills and videos ?

**Comment by MrBreadWater** [comment]
_**Before getting into this, I'd like to remind you that the basic functionality will be available for free in some way or another.**_

This topic is still being decided, but is definitely one of the more important questions. It has a long, complex line of reasoning behind it. 

I typed that entire line of reasoning, and every consideration behind it into a large comment. Then decided I could easily summarize it.

**TL;DR:** I don't know. It needs to make money somehow to sustain itself (servers, maintenance, etc) and hopefully help pay for new projects I plan on doing. Therefore it may very well include some paid features. However, that's not entirely decided yet. If I take that route, I will most likely include compensation for those who used the Data Collector plugin. 

And yes, I thoroughly believe that the finished project will greatly benefit the community. And the only way I can make it is if people submit their stills and videos.

**Comment by arthurlutz** [comment]
@MrBreadWater Thanks for taking the time to respond to this question.
