### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by arthurlutz** [MrBreadWater/project-kronos-data-collector#6]
Is the Kronos Data project GDPR compliant ? Maybe the storage location of the dataset should be more explicit in the description and the README. I had to go read the code to see that the data is sent to an S3 bucket. In which country is the data stored ?

**Comment by MrBreadWater** [comment]
Stored in U.S. This is GDPR compliant, as per [Recital 26.](https://gdpr-info.eu/recitals/no-26/) The only data being uploaded is the timelapses and photos, not even any metadata. Therefore, the data is not personally identifiable.

**Comment by arthurlutz** [comment]
I'm not sure this is as simple as that. One example is the AWS logs of access to the S3 buckets. 

* https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerLogs.html
* https://docs.aws.amazon.com/AmazonS3/latest/user-guide/server-access-logging.html

This might be disabled in your use case.

**Comment by MrBreadWater** [comment]
Server Access Logging is disabled with that in mind. I'm very careful to keep this 100% anonymous.
