### ISSUE TITLE
Sound contributions - detect failure with noise

### ISSUE THREAD

**Issue by arthurlutz** [MrBreadWater/project-kronos-data-collector#7]
With some printers, the soundwave can also be a valuable input of information as to wether the print is going well or not. For example if the spool is stuck, on some printer, we'll have a "clac clac clac" sound. Same goes when the Z-offset is incorrect and the plastic can't be pushed. 

Maybe if the octoprint setup has a soundcard/microphone, one could contribute a soundwave or a simplified / compressed version of a soundwave.

**Comment by MrBreadWater** [comment]
@arthurlutz The constant stream of "Issues" is getting to be a bit much. These are questions, not problems. Not only that, but you could have just at least consolidated this to one Issue. Could we discuss this via email or some other form of communication? I could do a Reddit AMA, or something else. But this isn't the correct forum for this. I have my email listed in my Bio, if that's the route you want to take.

**Comment by arthurlutz** [comment]
@MrBreadWater I'm sorry you perceived these issues as criticism or "a bit much". My intention was clarification of the some questions the project raises and the lack of other advertised means of communication, using the project tracker seemed legitimate. 

I hope this projects reaches its goals.

**Comment by MrBreadWater** [comment]
The questions were not a problem, in fact they were helpful in some cases. I was just extremely concerned about the sudden number of issue requests on my project, I was worried that something had gone horribly wrong. I'm totally open to questions, in fact I'll add a few forms of communication to the README file.
