### ISSUE TITLE
Detecing failure with sound

### ISSUE THREAD

**Issue by guysoft** [MrBreadWater/project-kronos-data-collector#8]
Hey,
Had this idea so I want to suggest it as early as in the design as possible.

There might be a really good basis to detect failure using sound. Sometimes a simple jerk can make the print fail, and that can be detected.

I am also working on a neural network that can detect this, given the correct data.
(Also going tomorrow to a hackathon for this, so if you have any input not I can test things out).

**Comment by MrBreadWater** [comment]
I may add sound as another feature later on -- however, most people don't already have microphones near their 3D printers so it will be harder to implement and convince people to set up than just the webcams.

**Comment by MrBreadWater** [comment]
@guysoft I'm gonna close this pretty soon unless there's more you'd like to discuss?

**Comment by guysoft** [comment]
Nope
