### ISSUE TITLE
Data collector or Neural Network?

### ISSUE THREAD

**Issue by arossbach10** [MrBreadWater/project-kronos-data-collector#9]
Is it just the data collector?
Where should the neural network be implemented?
Which NN framework and architecture is planned?

**Comment by MrBreadWater** [comment]
This is the Data Collector. The Neural Network will be implemented later on as a separate plugin or program. It won't run the network directly off the Pi's (not enough processing power and would interfere with printing), it will run on a server I've set up.

**Comment by aligator** [comment]
will it be possible to setup a own server?

**Comment by MrBreadWater** [comment]
@aligator No, sorry. Due to the nature of this project, it will remain private.
